### ISSUE TITLE
meta: 로켓쳇: RestAPI로 메시지 보내는 기능

### ISSUE THREAD

**Issue by khw7096** [digital-idea/OpenPipelineIO#1073]
## Todo

- [x] #1510
- [x] rocket chat token 입력하는 부분 만들기
- [x] #1512
- [x] #1514
- [x] #1516
- [x] rocket chat api 생성
- [x] 메시지 보내기 테스트
- [x] review와 연결하기
- [x] #1519
- [ ] 테스트 하면서 코드 리펙토링

## Reference
- inbox 개발전 적용하기
- https://docs.rocket.chat/quick-start/installing-and-updating

**Comment by khw7096** [comment]
#### 로켓쳇

- CSI와 같은 mongoDB를 사용하고 있다.
- 백업 솔루션 자체가 같아서 좋다.

#### AWS 마켓플레이스
- https://docs.rocket.chat/quick-start/installing-and-updating/paas-deployments/aws-marketplace
- 막상 기본 마켓 플레이스가 좋지는 않다.


#### CentOS

- https://docs.rocket.chat/quick-start/installing-and-updating/manual-installation/centos

#### AWS에도 해보자.(원격 서비스가 가능함.)
- rocketchat.lazypic.com
- https://docs.rocket.chat/quick-start/installing-and-updating/paas-deployments/aws

#### 엔서블을 이용한 설치
- https://docs.rocket.chat/quick-start/installing-and-updating/automation-tools/ansible
- https://galaxy.ansible.com/RocketChat/Server#readme
- https://github.com/RocketChat/Rocket.Chat.Ansible

#### 칼리리눅스
- https://docs.rocket.chat/quick-start/installing-and-updating/manual-installation/kali-linux

#### 도커
- https://medium.com/wematch/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4-%EB%A9%94%EC%8B%A0%EC%A0%80-%EB%A1%9C%EC%BC%93%EC%B1%97-rocket-chat-%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0-6a8b94dd843



#### 웹훅 API

레드마인, 젠킨스, 컨플루언스 등 다양한 서비스에서 특정 상황이 되면 
로켓챗에 메시지를 보내주었으면 요청이 있었다.

예를 들자면, 젠킨스에서 빌드가 완료되었을 때 빌드 정보를 로켓챗의 특정 채널 이나 사용자에게 전달해 주는 것이다.

대부분의 서비스에서는 이런 상황을 위해 슬랙에서 사용하는 웹훅API 를 지원하고 있다.
전달할 주소와 인증정보가 필요한데 이것을 슬랙에서 정의하고 서비스 설정에서 넣어서 연동하는 식이다.

로켓챗에서도 슬랙과 동일한 방식으로 웹훅API 연동이 가능하게 되어있다.

메뉴에서 Intergrations > New Integration > incomming webhook 이다.
이곳에서 정보(?)를 등록하고 나온 URL 을 젠킨스 쪽에 넣어주면 된다.

등록해야하는 설정 중 주요 설정은 아래와 같다.

Post to Channel
메시지를 보낼 채널 혹은 사용자의 이름이다. ex) #channel_id , @user_id

Post as
채팅창에 나오는 봇의 이름이다.

Script
일괄적으로 적용하고 싶은 스크립트가 있다면 적는다. 
일반적으로는 비워두고 웹훅을 보내는쪽에서 넣는편이다.

등록을 마치면 WebHook URL 과 Token 이 나온다.

Example 에 있는 예시를 이용하면 커맨드라인 상에서  CURL 을 이용해 메시지를 보낼 수도 있다.

```
curl -X POST -H 'Content-Type: application/json' --data '{"icon_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnQFLCYQ-rg_iJFXBzazZjUqMXTHPmTQ-AVU_JymsxleUHI1Oe","text":"Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"/images/integration-attachment-example.png","color":"#764FA5"}]}' http://[로켓챗주소]/hooks/[토큰]
```


#### Golang API
- https://github.com/badkaktus/gorocket <- rocket.chat 공식 문서에 있다.
- https://github.com/RocketChat/Rocket.Chat.Go.SDK
- 다른 채팅툴: https://golangexample.com/irc-slack-telegram-and-rocketchat-bot-written-in-golang/

**Comment by khw7096** [comment]
어플
![4D7B4FE1-0547-4C05-86BB-B6504EF9EFF4](https://user-images.githubusercontent.com/1149996/149263932-8014922b-1df8-4b81-99f0-6a50ffd86c30.png)
