### ISSUE TITLE
meta: 검색바에 team을 검색할 수 있는가?

### ISSUE THREAD

**Issue by khw7096** [digital-idea/OpenPipelineIO#1082]
- [x] 이후 pipelinestep으로 해결 될 수있다고 생각이 들었다.
- [x] Task 추가시 Pipelinestep을 추가할 수 있도록 옵션추가.
- [x] Task 변경시 pipelinestep default 값이 바꿀 수 있도록 만들기
- [x] add task시 pipelinestep이 같이 설정될 수 있도록 만들기
- [x] edit task시 pipelinestep이 같이 설정될 수 있도록 만들기
