### ISSUE TITLE
meta: 통계 리서치

### ISSUE THREAD

**Issue by khw7096** [digital-idea/OpenPipelineIO#1144]
#### 라이브러리 리서치
- https://www.monterail.com/blog/javascript-libraries-data-visualization
- https://github.com/grafana/grafana

**Comment by khw7096** [comment]
# 고려사항
- [x] 유연한 Status 로만 통계를 처리한다. 기존 status v1 지원
- [x] 새벽시간에 시간별로 처리하기 -> 실시간으로 변경하기
- [x] 분석용 mongodb 복제
- [x] dump 파일로 분석하기
- [ ] 상태별, 갯수별로 처리.

**Comment by khw7096** [comment]
- bi툴을 먼저 리서치해보기: https://www.finereport.com/kr/bi-솔루션/

**Comment by khw7096** [comment]
- [x] 통계툴을 만들게되더라도 통계 데이터를 뽑아가는 RestAPI는 필요하다.(검토완료)
