### ISSUE TITLE
mail: cc 부분 코드 점검하기.

### ISSUE THREAD

**Issue by khw7096** [digital-idea/OpenPipelineIO#1312]
#### Todo
- [x] Email 레귤러익스프레션 체크하기. 만약 없다면 작성하기
- [x] Email go test 코드 작성하기
- [x] form 데이터가 Email 일때와 아닐때를 구분 짓는 코드 부분 체크하기 RestAPI mailinfo
- [x] 크롬브라우저의 Gmail 핸들러 추가시 클릭하게 되는 아이콘의 명칭을 알아보기. -> Service handler icon / https://support.google.com/mail/thread/58665583/service-handler-icon-not-showing?hl=en
#### 상황체크
- pm부분에 데이터를 넣고
- cc 부분에 이메일을 적었을 때

클릭후 이메일 전송 폼 확인하기

**Comment by khw7096** [comment]
macOS 10.15.4 에서 mailto 프로토콜이 작동되지 않음. 체크해보기

**Comment by khw7096** [comment]
_blink로 이메일이 가는 것이 차단된다. 사파리 브라우저는 기본적으로 팝업을 차단하기 때문임

**Comment by khw7096** [comment]
크롬에서는 mailto 핸들러를 크롬 내부에서 설정하니 각 브라우저마다 다르게 설정할 필요가 있어보인다.

**Comment by khw7096** [comment]
메일 항목에 크롬이 설정되어 있어서 그렇다.

![image](https://user-images.githubusercontent.com/1149996/126579668-012bd97f-cafd-4556-ae89-b0806edfaf7b.png)

**Comment by khw7096** [comment]
메일 설정을 mail로 다시 바꾸기

![image](https://user-images.githubusercontent.com/1149996/126579704-bc4b4796-8364-45f6-841e-b1e1b52c309b.png)

참고자료: https://discussions.apple.com/thread/6993022

**Comment by khw7096** [comment]
사파리와 크롬을 끄고 시간이 조금 흐르면 시스템 설정에서 Email 처리가 mail 툴로 돌아온다.

**Comment by khw7096** [comment]
기본적인 문제를 해결했다. 이제 디버그를 시작할 수 있다.

**Comment by khw7096** [comment]
CC 메일 체크시 만약 이메일 포멧이라면 해당 이메일을 바로 사용하고 이메일 방식이 아니라면, 유저의 email을 구해서 넣는 코드로 작성하면 더 좋을것 같다.

**Comment by khw7096** [comment]
- [ ] Email go test 코드 작성하기
- [ ] Email 레귤러익스프레션 체크하기. 만약 없다면 작성하기
- [ ] form 데이터가 Email 일때와 아닐때를 구분 짓는 코드 부분 체크하기
- [ ] 크롬브라우저의 Gmail 핸들러 추가시 클릭하게 되는 아이콘의 명칭을 알아보기
