### ISSUE TITLE
자료구조 추가하기: NetflixID

### ISSUE THREAD

**Issue by khw7096** [digital-idea/OpenPipelineIO#1322]
#### Reference
- int64 형태로 입력하기. 일반적으로 숫자 6자리
    - 참고자료: https://stackoverflow.com/questions/6878590/the-maximum-value-for-an-int-type-in-go
    - 참고자료: https://partnerhelp.netflixstudios.com/hc/en-us/articles/360057627473-VFX-Shot-and-Version-Naming-Recommendations

#### TODO
- [x] NetflixID 자료구조 추가하기
- [x] `E` 버튼을 눌렀을 때 NetflixID 입력 폼만들기
- [x] RestAPI 제작
- [x] 실제로 값이 설정될 수 있도록 하기
- [x] RestAPI 메뉴얼 작성하기
- [x] RestAPI 바닐라 js로 리펙토링
- [x] Detail view 표기하기
- [x] cmd 모드로 Scan Data 처리시 netflixID가 들어갈 수 있도록 옵션 추가하기.
- [x] Add shot, add asset 시 NetflixID 입력될 수 있도록 하기
    - [x] 부트스트랩5의 CSS 의 버튼 설정보기
    - [x] 버튼을 가로로 늘리기
    - [x] 스위치 배경색 변경
    - [x] addshot, addasset에서 input.js를 로딩하는 것은 비효율적이다. 하지만 상단 메뉴가 작동되어야 한다.
    - [x] netflixid 검색되어야 한다. string 으로 변경

**Comment by khw7096** [comment]
uint32 사이즈가 좋아보인다. size 4 byte

**Comment by khw7096** [comment]
바닐라 js로 fetch 하는 방법

https://gomakethings.com/how-to-send-data-to-an-api-with-the-vanilla-js-fetch-method/

**Comment by khw7096** [comment]
cmd 제작을 위해 설정시 flag 옵션에서 uint32에 대해 러스콕스의 의견이 담긴 글: https://github.com/golang/go/issues/26545

**Comment by khw7096** [comment]
uint64 는 8byte

**Comment by khw7096** [comment]
- 부트스트랩5의 CSS 의 버튼 설정보기
- 버튼을 가로로 늘리기
- 스위치 배경색 변경
- input.js를 로딩하는 것은 비효율적이다.
- netflixid 검색되어야 한다.
