### ISSUE TITLE
meta: 검색바 개선

### ISSUE THREAD

**Issue by khw7096** [digital-idea/OpenPipelineIO#1517]
- [x] 샷네임으로 검색시 검색한 샷 네임을 가진 샷만 불러올수 있는 옵션이 있으면 좋겠어요. 검색 정보로 서치가 모두 되는 상황이라 컷이 많으면 정작 찾고 싶은 샷은 거기서 또 확인하며 찾아야 하는 상태예요.
- [x] 태그가 많은 프로젝트에서 샷 검색시 샷네임이 가려져요. (그렇다고 태그를 작게 하지는 않았으면 좋겠어요)
- 검색후 서치박스 숨기고 확인 후 다시 검색하려니 서치박스를 다시 켜야 하는 불편함이 있습니다. 서치박스는 유지할 수 없을까요?
- 서치박스 숨긴후 새로고침을 하면 서치박스가 다시 나타나요. 숨긴상태에서 새고하면 그상태가 유지 될 수 있으면 좋겠어요.
- [x] 보이는지 안보이는지 search box visable cookie 추가하기
- [x] 페이지를 새로고침할 때 cookie를 기반으로 보이도록 또는 안보이도록 만들기

**Comment by khw7096** [comment]
- name: 으로 검색하는 방법에 대한 Youtube 찍어서 올리기
