### ISSUE TITLE
meta: Partner 관리페이지 제작

### ISSUE THREAD

**Issue by khw7096** [digital-idea/OpenPipelineIO#1557]
- [x] #1558
- [x] #1560
- [x] Partner 페이지 제작
- [x] #1623
- [x] 파트너 수정기능 제작: title을 클릭할 때 Edit modal이 뜬다.
- [x] 모양 다듬기: +버튼, +버튼 박스 색상, 삭제 기능 색상과 모양
- [x] #1625
- [x] 파트너 클릭시 모달에 값이 설정될 수 있도록 만들기
- [x] 파트너 수정시 Put 기능이 작동되도록 만들기
- [x] Partner UX 삭제 테스트

**Comment by khw7096** [comment]
- https://knowledge.autodesk.com/support/shotgrid/learn-explore/caas/CloudHelp/cloudhelp/ENU/SG-Producer/files/pr-reviews/SG-Producer-pr-reviews-pr-client-review-shotgun-html-html.html
- https://knowledge.autodesk.com/support/shotgrid/learn-explore/caas/CloudHelp/cloudhelp/ENU/SG-Migration/files/mi-migration/SG-Migration-mi-migration-mi-admin-user-account-html-html.html

**Comment by khw7096** [comment]
#### Shotgrid 항목
- 이름
- 이메일
- 로고
- 접근제한일
- 접속후 패스워드 인증
- Playlist를 Lock 하는 기능
- email 알람시 썸네일을 추가하는 기능
- 코멘트를 보고 생성하는 기능
- 오리지널 데이터를 업로드 다운로드 할 수 있는 기능
- 클라이언트 리뷰사이트 활성화
- 접근제한 IP 리스트
- 모든 공유 재생 목록에 비밀번호 인증 필요
- transcoded된 영상 또는 사진 다운로드 기능

## Reference
- https://knowledge.autodesk.com/support/shotgrid/learn-explore/caas/CloudHelp/cloudhelp/ENU/SG-Producer/files/pr-reviews/SG-Producer-pr-reviews-pr-client-review-shotgun-html-html.html
