### ISSUE TITLE
통계: 선택한 프로젝트들의 진행률의 합이 보이도록 하기

### ISSUE THREAD

**Issue by baesy0** [digital-idea/OpenPipelineIO#1731]
선택한 프로젝트들의 진행률 합 보기

**Comment by khw7096** [comment]
#### Todo
- [x] 합이 표현될 챠트 div를 추가하기
- [x] obj를 만들고 프로젝트가 체크되었을 때를 위한 attribute 추가하기
- [x] obj 값을 이용해서 실제 챠트 렌더링하기
