### ISSUE TITLE
meta: 썸네일 이미지를 이용한 샷 생성 논의

### ISSUE THREAD

**Issue by khw7096** [digital-idea/OpenPipelineIO#1757]
- [x] 폴더 트리 만들고 확인하기
- [x] 좀더 자동으로 할 수 있는 방법을 고민하기.
- [x] #1764
- [x] drag and drop library 리서치
    - https://stackoverflow.com/questions/3590058/does-html5-allow-drag-drop-upload-of-folders-or-a-folder-tree
    - https://protonet.com/blog/html5-experiment-drag-drop-of-folders/
    - https://www.plupload.com
    - https://www.plupload.com/examples/runtimes
    - https://codepen.io/cagerattler/pen/OZqdBy
- [x] exr parser library 리서치
    - https://github.com/mokiat/goexr
    - oiio방식
- [x] Exr 처리 RestAPI
- [x] oiio셋팅
- [x] 로컬에서 처리해서 jpg로 올리는게 가볍지만, exr을 직접 지원하는 것도 좋은 방법 같다.

**Comment by khw7096** [comment]
```javascript
var dropArea = document.querySelector("#dropArea");

dropArea.addEventListener(
  "dragover",
  function(e) {
    e = e || event;
    e.preventDefault();
  },
  false
);

dropArea.addEventListener(
  "drop",
  function(event) {
    var items = event.dataTransfer.items;
    console.log(items)

    event.preventDefault();

    getFilesDataTransferItems(items).then(files => {
      var rawOutput = JSON.stringify(files),
        output = rawOutput
          .substring(1, rawOutput.length - 1)
          .replace(/},/g, "}<br/>")
          .replace(/\[/g, "[<div class='folder'>")
          .replace(/\]/g, "]</div>");

      document.querySelector("#output").innerHTML = output;
    });
  },
  false
);

function getFilesDataTransferItems(dataTransferItems) {
  function traverseFileTreePromise(item, path = "", folder) {
    return new Promise(resolve => {
      if (item.isFile) {
        item.file(file => {
          console.log(file.name) // 이 포인트에서 생각해보기
          file.filepath = path || "" + file.name; //save full path
          folder.push(file);
          resolve(file);
        });
      } else if (item.isDirectory) {
        let dirReader = item.createReader();
        dirReader.readEntries(entries => {
          let entriesPromises = [];
          subfolder = [];
          folder.push({ name: item.name, subfolder: subfolder });
          for (let entr of entries)
            entriesPromises.push(
              traverseFileTreePromise(entr, path || ""  + item.name + "/", subfolder)
            );
          resolve(Promise.all(entriesPromises));
        });
      }
    });
  }

  let files = [];
  return new Promise((resolve, reject) => {
    let entriesPromises = [];
    for (let it of dataTransferItems)
      entriesPromises.push(
        traverseFileTreePromise(it.webkitGetAsEntry(), null, files)
      );
    Promise.all(entriesPromises).then(entries => {
      resolve(files);
    });
  });
}


```

**Comment by khw7096** [comment]
테스트케이스1
```
20220809
├─ 109S042_0010/
├─ 109S042_0020/
│  ├─ 109S042_0010.000001.exr
│  ├─ 109S042_0010.000002.exr
│  ├─ 109S042_0010.000003.exr
├─ 109S042_0030/
│  ├─ 109S042_0030.000001.exr
│  ├─ 109S042_0030.000001.exr
├─ 109S042_0040
├─ 109S042_0050
```

테스트 케이스2
```
/20220809/plate/exr/109S042_0020/109S042_0020.000001.exr
/20220809/plate/exr/109S042_0030/109S042_0030.000001.exr
/20220809/plate/exr/109S042_0030/109S042_0030.000002.exr
```

참고: https://ascii-tree-generator.com

**Comment by khw7096** [comment]
일단 썸네일을 올리는 형태를 1차로 작성, 이후 좀더 편리한 방법을 고민해보기.

**Comment by khw7096** [comment]
이 방법은 ScanPlate에서 개발중이다.
