### ISSUE TITLE
인트라넷, 클라우드에서는 속도가 느려질 수 있다. 페이지 구현하기.

### ISSUE THREAD

**Issue by khw7096** [digital-idea/OpenPipelineIO#400]
#### 리펙토링 진행규칙
- 기존 함수를 놔두고 새로 복사해서 함수 만들기

#### Reference
- Limit: http://bazaar.launchpad.net/+branch/mgo/v2/view/head:/session.go#L2080
- Skip
- https://stackoverflow.com/questions/45077177/golang-mongodb-sorting-alphabetically-with-skip-and-limit

#### Todo
- [x] adminsetting에 20, 50, 100 셋팅 옵션 넣기.
- [x] url에 page 인수 추가하기, 보려고 하는 페이지는 검색옵션이기 때문에 SearchOpition 자료구조에 Page를 추가함.
- [ ] inputmode 핸들러 데이터를 페이지로 셋팅하기, limit, skip 활용
- [ ] 쿼리가 들어왔을 때 총 검색 갯수만 구하는 함수 제작
- [ ] 예상페이지 수 구하기: 총 검색갯수와 Adminsetting의 보여야 하는 페이지수를 알면 예상페이지 수 를 구할 수 있다.
- [ ] 페이지 template 만들기

**Comment by khw7096** [comment]
20, 50, 100 셋팅 옵션 넣기.

**Comment by khw7096** [comment]
이슈번호를 갱신하기 위해 새로운 이슈로 다시 생성
