### ISSUE TITLE
통계: 리서치 2단계

### ISSUE THREAD

**Issue by khw7096** [digital-idea/OpenPipelineIO#464]
### TODO
- [x] #1638

### 라이브러리
- https://golangexample.com/a-graceful-data-visualizing-library-for-golang/
- https://thenextweb.com/dd/2015/06/12/20-best-javascript-chart-libraries/
- https://www.highcharts.com/demo/columnrange
### 분류
작업자 현황, 팀별

- 이름, 상태, 갯수
- 기간별 몰려있는 샷수
- 이름별 status 갯수

**Comment by khw7096** [comment]
![image](https://user-images.githubusercontent.com/1149996/73584182-02472e00-44da-11ea-8f01-06b447ddac88.png)

팀장님이 필요한 정보

**Comment by khw7096** [comment]
자신에 대한

- [x] 테스크 갯수
- [x] 프로젝트별 갯수
- [x] 상태별 갯수

**Comment by khw7096** [comment]
총 모든 상황을 알 수 있는 통계페이지, 클릭하면 세부를 알 수 있는 페이지, 다시 클릭하면 세부를 알 수 있는 페이지

**Comment by khw7096** [comment]
![image](https://user-images.githubusercontent.com/1149996/169675187-6ed7d831-8cc5-4126-b129-87ee4a1c6417.png)
![image](https://user-images.githubusercontent.com/1149996/169675195-a2126fa3-4e07-49f3-8f27-ef8ea83835e8.png)

**Comment by khw7096** [comment]
# 회의록
- [x] 파트별 진행률(pipelinestep) %
- [x] 어느 프로젝트가 몇컷이 남았는지 조사하기
- [x] 컴프팀 팀별(pipelinestep) 프로젝트 진행율%
- [x] 한달에 몇 샷을 해야하는지 다음달에 몇 샷을 해야하는 지
- RestAPI를 작성한다. task 방식, tag 방식, pipelinestep 방식, statusv2 방식을 따로 구축한다.
