### ISSUE TITLE
가변 status에서 샷이 생성될 때 하드코딩된 부분 기능 수정하기.

### ISSUE THREAD

**Issue by khw7096** [digital-idea/OpenPipelineIO#972]
- studioG 상황에 대한 테스트 진행하기.
- 샷,에셋 생성시 어떠한 status를 기본 설정으로 사용될 수 있을지 결정하는 옵션을 추가하기.

#### Todo
- [x] status 자료구조에서 initStatus 자료구조 만들기. 모든 Status 리스트중에서 오직 하나여야 한다. bool
- [x] Web에서 옵션 만들기
- [x] initStatus의 ID를 가지고오는 함수를 만들기.
- [x] shot, asset을 생성할 때 최초 initstatus 설정되도록 만들기.
- [x] setDefaultStatus.sh 에 setDefaultStatus 설정할 수 있도록 하기.
- [x] devmode 모드일때는 무조껀 v2 검색창으로 실행되도록 하기.

**Comment by khw7096** [comment]
Check Status List

- confirm
- keep
- ok
- qc
- retake
- wait <initStatus
- hold
- ing
- omit
